openapi: 3.0.0
components:
  schemas:
    CreateCharacterRequest:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        gender:
          type: string
        homePlanet:
          type: strin
  securitySchemes: {}
info:
  title: My API
  description: This is my API documentation
  version: '1'
paths: {}
